version: '3.7'

services:

  client:
    container_name: simple_vue_app
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    #env_file:
    #  - ./env/dev/.env